[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
ast = true
build_info = true
fs_permissions = [{ access = "read-write", path = "./data" }, { access = "read", path = "out" }]
evm_version = "cancun"
extra_output = ["storageLayout"]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
